### ISSUE TITLE
[ISSUE] Adding and Removing devices from user accounts

### ISSUE THREAD

**Issue by Prot0ast** [Prot0ast/Skillstorm-Project2#3]
Description of task: Users must be able to add and remove devices from their accounts

Completion requirements for task:
- [x] Add a method for users to add devices to their account
- [x] Add a method for users to remove devices from their account
 
Dependencies:
- [x] Users should already be able to access their accounts (#4 )
- [x] The different phone plans should already restrict how many devices users can add (#2 )
- [x] A devices base should already be implemented that specifies unique phone numbers (#6 )
